### ISSUE TITLE
Waht is the speed of freqt_GO?

### ISSUE THREAD

**Issue by candlewill** [MU94W/SPTK-GO#1]
In addition to the acceleration of `mlpg`, I saw that you also accelerated `freqt`. I want to know how much acceleration can be achieved for `freqt`. Thank you.

**Comment by MU94W** [comment]
speedup only ~ 1.217, since no new algorithm adopted.
but ... there are some calculation mistakes in freqtGO.
I will debug later.

**Comment by MU94W** [comment]
@candlewill 
speedup only ~1.217, since no new algorithm adopted.
but ... there are some calculation mistakes in freqtGO.
I will debug later.

**Comment by candlewill** [comment]
Thanks.
